application: kjuarbeh
version: 2
runtime: go
api_version: 2

handlers:
- url: /
  script: _go_app
- url: /static
  static_dir: static
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
